FROM local:geth-node-base

CMD geth --identity "alexykot" --datadir "/root/.ethereum" --cache 64 --port 30303 --maxpeers 1024 --maxpendpeers 128 --nat "any" --rpc --rpccorsdomain "*" --rpcaddr "0.0.0.0" --rpcport 8545 --rpcapi "admin,db,eth,debug,miner,net,shh,txpool,personal,web3" --shh


